<a href="https://colab.research.google.com/github/parulian-johannes/Tugas-metnum/blob/main/Tugasmetnum-parulianjohannes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

def inverse_matrix(matrix):
    # Cek apakah matriks adalah matriks persegi
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matriks harus berbentuk persegi untuk memiliki matriks balikan")

    # Menggunakan fungsi inv dari NumPy untuk menghitung matriks balikan
    try:
        inverse = np.linalg.inv(matrix)
        return inverse
    except np.linalg.LinAlgError:
        raise ValueError("Matriks tidak dapat diubah menjadi matriks balikan. Pastikan matriks tidak singular.")

# Contoh penggunaan
A = np.array([[1, 2], [3, 4]])
print("Matriks A:")
print(A)

try:
    A_inverse = inverse_matrix(A)
    print("\nMatriks Balikan dari A:")
    print(A_inverse)
except ValueError as e:
    print(e)


Matriks A:
[[1 2]
 [3 4]]

Matriks Balikan dari A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Mendekomposisi matriks A menjadi matriks L dan U
    for i in range(n):
        L[i, i] = 1
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]

    return L, U

# Contoh penggunaan
A = np.array([[2, -1, 3], [4, 4, -2], [6, 5, 1]])
print("Matriks A:")
print(A)

L, U = lu_decomposition(A)
print("\nMatriks Lower (L):")
print(L)
print("\nMatriks Upper (U):")
print(U)


Matriks A:
[[ 2 -1  3]
 [ 4  4 -2]
 [ 6  5  1]]

Matriks Lower (L):
[[1.         0.         0.        ]
 [2.         1.         0.        ]
 [3.         1.33333333 1.        ]]

Matriks Upper (U):
[[ 2.         -1.          3.        ]
 [ 0.          6.         -8.        ]
 [ 0.          0.          2.66666667]]


In [10]:
import numpy as np

def crout_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for j in range(n):
        U[j, j] = 1  # Diagonal utama matriks U adalah 1
        for i in range(j, n):
            sum_val = sum(L[i, k] * U[k, j] for k in range(i))
            L[i, j] = A[i, j] - sum_val
        for i in range(j+1, n):
            sum_val = sum(L[j, k] * U[k, i] for k in range(j))
            U[j, i] = (A[j, i] - sum_val) / L[j, j]

    return L, U

# Contoh penggunaan
A = np.array([[2, -1, 3], [4, 4, -2], [6, 5, 1]])
print("Matriks A:")
print(A)

L, U = crout_decomposition(A)
print("\nMatriks Lower (L):")
print(L)
print("\nMatriks Upper (U):")
print(U)


Matriks A:
[[ 2 -1  3]
 [ 4  4 -2]
 [ 6  5  1]]

Matriks Lower (L):
[[2.         0.         0.        ]
 [4.         6.         0.        ]
 [6.         8.         2.66666667]]

Matriks Upper (U):
[[ 1.         -0.5         1.5       ]
 [ 0.          1.         -1.33333333]
 [ 0.          0.          1.        ]]
